spring.application.name=Challenge-Foro-Hub

spring.datasource.url=jdbc:mysql://localhost/foro_hub
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=448400121qazxsw2Lucas

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.error.include-stacktrace=never

api.security.token.secret=${JWT_SECRET:12345678}
spring.security.user.name=admin
spring.security.user.password=1234