CREATE TABLE IF NOT EXISTS topico (
	id INT UNIQUE NOT NULL AUTO_INCREMENT PRIMARY KEY,
	titulo VARCHAR(100) NOT NULL,
	mensaje VARCHAR(255) NOT NULL,
	fechaCreacion DATETIME NOT NULL,
	status_topico VARCHAR(20) NOT NULL DEFAULT 'inactivo',
	autor VARCHAR(50) NOT NULL,
	curso VARCHAR(50) NOT NULL
);